//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebProject.PersonServices {
    using System;
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonServices.CRUDServiceSoap")]
    public interface CRUDServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPersonByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPersonByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPersonByName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetPersonByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPersons", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPersons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPersons", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetPersonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePerson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SavePerson(MvcWebProject.PersonServices.Person pers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePerson", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SavePersonAsync(MvcWebProject.PersonServices.Person pers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePerson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeletePerson(int personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePerson", ReplyAction="*")]
        System.Threading.Tasks.Task DeletePersonAsync(int personId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Person : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string surnameField;
        
        private int ageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("Surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
                this.RaisePropertyChanged("Age");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CRUDServiceSoapChannel : MvcWebProject.PersonServices.CRUDServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRUDServiceSoapClient : System.ServiceModel.ClientBase<MvcWebProject.PersonServices.CRUDServiceSoap>, MvcWebProject.PersonServices.CRUDServiceSoap {
        
        public CRUDServiceSoapClient() {
        }
        
        public CRUDServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRUDServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRUDServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRUDServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetPersonByName(string name) {
            return base.Channel.GetPersonByName(name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetPersonByNameAsync(string name) {
            return base.Channel.GetPersonByNameAsync(name);
        }
        
        public System.Data.DataTable GetPersons() {
            return base.Channel.GetPersons();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetPersonsAsync() {
            return base.Channel.GetPersonsAsync();
        }
        
        public string SavePerson(MvcWebProject.PersonServices.Person pers) {
            return base.Channel.SavePerson(pers);
        }
        
        public System.Threading.Tasks.Task<string> SavePersonAsync(MvcWebProject.PersonServices.Person pers) {
            return base.Channel.SavePersonAsync(pers);
        }
        
        public void DeletePerson(int personId) {
            base.Channel.DeletePerson(personId);
        }
        
        public System.Threading.Tasks.Task DeletePersonAsync(int personId) {
            return base.Channel.DeletePersonAsync(personId);
        }
    }
}
